### ISSUE TITLE
[Perfil do Usuário] Criar questionário

### ISSUE THREAD

**Issue by gustable42** [Interacao-Humano-Computador/2019.2-Samuel-Pereira-Imobiliario#1]
É necessário desenvolver um questionário para entender melhor o perfil do usuário médio da Samuel Pereiro Escritório Imobiliário.

<strong>Tarefas</strong>
- [x] Criar o formulário no Google Forms
- [ ] Divulgar o formulário criado para o maior número de pessoas de diferentes contextos o respondam

<strong>Critérios de Aceitação</strong>
- [x] Ao menos 20 respostas no formulário
- [ ] Ser possível gerar um perfil de usuário com os dados coletados

**Comment by gustable42** [comment]
Questionário criado usando a ferramenta Google Forms:
https://forms.gle/2rP1xB7tNoVfqZD86

Espero feedback dos outros membros para começar a divulgação dele

**Comment by Wictorgirardi** [comment]
Muito bom @gustable42! Vc recebeu um retorno 200 do server, Parabens!
