### ISSUE TITLE
[Requisitos de IHC] Usar formulário já feito para elicitação de requisitos

### ISSUE THREAD

**Issue by gustable42** [Interacao-Humano-Computador/2019.2-Samuel-Pereira-Imobiliario#10]
Com o formulário criado e utilizado na issue #1 , usar os dados coletados para levantar ideias para requisitos voltados a IHC

<strong>Tarefas</strong>
- [ ] Utilizar as informações do questionário para definir ainda melhor os perfis de usuário
- [ ] Documentos estarem de acordo com a base teórica dada em sala de aula e no material de apoio

**Comment by lucasgandac** [comment]
Levantamento de requisitos devidamente feito
