### ISSUE TITLE
[Requisitos de IHC] Definir outros métodos de elicitação e executá-los 

### ISSUE THREAD

**Issue by gustable42** [Interacao-Humano-Computador/2019.2-Samuel-Pereira-Imobiliario#11]
<strong>Tarefas</strong
- [ ] Definir os métodos de elicitação usados

<strong>Critérios de aceitação</strong
- [ ] Documentos estarem de acordo com a base teórica dada em sala de aula e no material de apoio
- [ ] Observar se os métodos usados foram bem utilizados

**Comment by lucasgandac** [comment]
Definicao de metodos de elicitacao feita
