### ISSUE TITLE
[Protótipo de Papel] Criar o protótipo de papel e digitalizá-lo

### ISSUE THREAD

**Issue by gustable42** [Interacao-Humano-Computador/2019.2-Samuel-Pereira-Imobiliario#5]
<strong>Tarefas</strong>
- [x] Landing page
- [x] Página de imóvel
- [x] Resultado de uma busca
- [x] Cadastro e edição de imóveis pela dashboard
- [x] Listagem de Imóveis pela dashboard

<strong>Critérios de Aceitação</strong>
- [x] Todas as 5 telas devem ter sido desenhadas e deixado claro como elas se comunicam
- [x] Documentos estarem de acordo com a base teórica dada em sala de aula e no material de apoio.

**Comment by gustable42** [comment]
Esperando a revisão dos outros membros do grupo

**Comment by Andreabenf** [comment]
Muito bom!
